const messages = [
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'24a2d801-3f2c-473d-a28e-3f5cb332613d',QueryString:'tress%20de%20la%20mer%20emeraude',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'tress%20de%20la%20mer%20emeraude',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))"> Tress de la mer émeraude</a>, Brandon Sanderson</p><img src="https://m.media-amazon.com/images/I/81VELqJKuFL._UF1000,1000_QL80_.jpg" alt="Tress" style="width:100px;"> <p>Tress vit sur une petite île isolée au beau milieu d'un océan... de spores. Simple laveuse de vitres, elle partage néanmoins une belle complicité avec Charlie, le fils du duc, et est secrètement amoureuse de lui. Quand celui-ci disparaît, la jeune femme décide de partir à sa recherche. C'est le début d'un périple au bout du monde, où l'on retrouve tous les ingrédients qui font le sel des grandes aventures : des contrebandiers de la pire espèce, une sorcière malintentionnée, un redoutable dragon, des pirates sales et méchants (ou pas), et même un rat qui parle... <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur adulte; SAND SF <br> <br> Bibliothèque Sainte Musse, Secteur adulte, SAND SF </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:2,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'0f0149ef-bbe5-4293-959d-d5425b12d199',QueryString:'le%20petit%20guide%20de%20miss%20percy',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20petit%20guide%20de%20miss%20percy',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))"> Le petit guide de Miss Percy ou Comment élever un dragon britannique</a>, Quenby Olson </p><img src="https://milady.fr/media/cache/book/07/9782811230807.jpg" alt="Miss Percy" style="width:100px;"> <p>Mildred Percy mène une vie tranquille, jusqu'au jour où son grand-oncle lui lègue un oeuf de dragon. Alors qu'elle élève le petit dragon, elle doit faire face à ses sentiments naissants pour un pasteur. <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur adulte; OLSO SF T.01 </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:5,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:e52b15bf-8b51-4036-ad12-2c89e5f3d1d7,QueryString:'le%20chateau%20de%20hurle',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20chateau%20de%20hurle',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Le château de hurle</a>, Diana Wynne Jones</p><img src="https://m.media-amazon.com/images/I/71yS-KZw9eL._UF1000,1000_QL80_.jpg" alt="Château" style="width:100px;"> <p> Aînée de trois filles, Sophie vit dans un univers où la magie fait partie du quotidien. Maudite par une sorcière et transformée en vieille dame, elle rencontre le magicien Hurle qui habite un château volant. Ils se lancent tous deux dans une série d'aventures, Sophie tentant de se libérer de son mauvais sort. Roman adapté au cinéma par H. Miyazaki sous le titre Le château ambulant. <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur jeunesse; JONE SF <br> <br> Bibliothèque Port Marchand, Secteur jeunesse, JONE R T.01 </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:c5578de6-ed4d-43c7-8bbc-60101b1e8d2b,QueryString:'sorcery%20of%20thorns',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'sorcery%20of%20thorns',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Sorcery of Thorns</a>, Margaret Rogerson</p><img src="https://m.media-amazon.com/images/I/71AuWgN2H7L._UF1000,1000_QL80_.jpg" alt="Sorcery" style="width:100px;"> <p>Peu de temps après le passage du sorcier Nathaniel Thorn à la grande bibliothèque d'Austermeer, l'un des ouvrages se transforme en monstre, semant mort et destruction. Accusée de l'avoir libérée, Elisabeth doit comparaître devant la justice. Prise au coeur d'une conspiration, elle n'a d'autre choix que de se tourner vers Nathaniel et son mystérieux serviteur, Silas. <br> <br> Bibliothèque Sainte Musse, Secteur jeunesse, ROGE R </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'24a2d801-3f2c-473d-a28e-3f5cb332613d',QueryString:'tress%20de%20la%20mer%20emeraude',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'tress%20de%20la%20mer%20emeraude',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))"> Tress de la mer émeraude</a>, Brandon Sanderson</p><img src="https://m.media-amazon.com/images/I/81VELqJKuFL._UF1000,1000_QL80_.jpg" alt="Tress" style="width:100px;"> <p>Tress vit sur une petite île isolée au beau milieu d'un océan... de spores. Simple laveuse de vitres, elle partage néanmoins une belle complicité avec Charlie, le fils du duc, et est secrètement amoureuse de lui. Quand celui-ci disparaît, la jeune femme décide de partir à sa recherche. C'est le début d'un périple au bout du monde, où l'on retrouve tous les ingrédients qui font le sel des grandes aventures : des contrebandiers de la pire espèce, une sorcière malintentionnée, un redoutable dragon, des pirates sales et méchants (ou pas), et même un rat qui parle... <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur adulte; SAND SF <br> <br> Bibliothèque Sainte Musse, Secteur adulte, SAND SF </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:2,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'0f0149ef-bbe5-4293-959d-d5425b12d199',QueryString:'le%20petit%20guide%20de%20miss%20percy',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20petit%20guide%20de%20miss%20percy',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))"> Le petit guide de Miss Percy ou Comment élever un dragon britannique</a>, Quenby Olson </p><img src="https://milady.fr/media/cache/book/07/9782811230807.jpg" alt="Miss Percy" style="width:100px;"> <p>Mildred Percy mène une vie tranquille, jusqu'au jour où son grand-oncle lui lègue un oeuf de dragon. Alors qu'elle élève le petit dragon, elle doit faire face à ses sentiments naissants pour un pasteur. <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur adulte; OLSO SF T.01 </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:5,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:e52b15bf-8b51-4036-ad12-2c89e5f3d1d7,QueryString:'le%20chateau%20de%20hurle',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20chateau%20de%20hurle',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Le château de hurle</a>, Diana Wynne Jones</p><img src="https://m.media-amazon.com/images/I/71yS-KZw9eL._UF1000,1000_QL80_.jpg" alt="Château" style="width:100px;"> <p> Aînée de trois filles, Sophie vit dans un univers où la magie fait partie du quotidien. Maudite par une sorcière et transformée en vieille dame, elle rencontre le magicien Hurle qui habite un château volant. Ils se lancent tous deux dans une série d'aventures, Sophie tentant de se libérer de son mauvais sort. Roman adapté au cinéma par H. Miyazaki sous le titre Le château ambulant. <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur jeunesse; JONE SF <br> <br> Bibliothèque Port Marchand, Secteur jeunesse, JONE R T.01 </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:c5578de6-ed4d-43c7-8bbc-60101b1e8d2b,QueryString:'sorcery%20of%20thorns',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'sorcery%20of%20thorns',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Sorcery of Thorns</a>, Margaret Rogerson</p><img src="https://m.media-amazon.com/images/I/71AuWgN2H7L._UF1000,1000_QL80_.jpg" alt="Sorcery" style="width:100px;"> <p>Peu de temps après le passage du sorcier Nathaniel Thorn à la grande bibliothèque d'Austermeer, l'un des ouvrages se transforme en monstre, semant mort et destruction. Accusée de l'avoir libérée, Elisabeth doit comparaître devant la justice. Prise au coeur d'une conspiration, elle n'a d'autre choix que de se tourner vers Nathaniel et son mystérieux serviteur, Silas. <br> <br> Bibliothèque Sainte Musse, Secteur jeunesse, ROGE R </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'24a2d801-3f2c-473d-a28e-3f5cb332613d',QueryString:'tress%20de%20la%20mer%20emeraude',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'tress%20de%20la%20mer%20emeraude',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))"> Tress de la mer émeraude</a>, Brandon Sanderson</p><img src="https://m.media-amazon.com/images/I/81VELqJKuFL._UF1000,1000_QL80_.jpg" alt="Tress" style="width:100px;"> <p>Tress vit sur une petite île isolée au beau milieu d'un océan... de spores. Simple laveuse de vitres, elle partage néanmoins une belle complicité avec Charlie, le fils du duc, et est secrètement amoureuse de lui. Quand celui-ci disparaît, la jeune femme décide de partir à sa recherche. C'est le début d'un périple au bout du monde, où l'on retrouve tous les ingrédients qui font le sel des grandes aventures : des contrebandiers de la pire espèce, une sorcière malintentionnée, un redoutable dragon, des pirates sales et méchants (ou pas), et même un rat qui parle... <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur adulte; SAND SF <br> <br> Bibliothèque Sainte Musse, Secteur adulte, SAND SF </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:2,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'0f0149ef-bbe5-4293-959d-d5425b12d199',QueryString:'le%20petit%20guide%20de%20miss%20percy',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20petit%20guide%20de%20miss%20percy',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))"> Le petit guide de Miss Percy ou Comment élever un dragon britannique</a>, Quenby Olson </p><img src="https://milady.fr/media/cache/book/07/9782811230807.jpg" alt="Miss Percy" style="width:100px;"> <p>Mildred Percy mène une vie tranquille, jusqu'au jour où son grand-oncle lui lègue un oeuf de dragon. Alors qu'elle élève le petit dragon, elle doit faire face à ses sentiments naissants pour un pasteur. <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur adulte; OLSO SF T.01 </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:5,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:e52b15bf-8b51-4036-ad12-2c89e5f3d1d7,QueryString:'le%20chateau%20de%20hurle',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20chateau%20de%20hurle',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Le château de hurle</a>, Diana Wynne Jones</p><img src="https://m.media-amazon.com/images/I/71yS-KZw9eL._UF1000,1000_QL80_.jpg" alt="Château" style="width:100px;"> <p> Aînée de trois filles, Sophie vit dans un univers où la magie fait partie du quotidien. Maudite par une sorcière et transformée en vieille dame, elle rencontre le magicien Hurle qui habite un château volant. Ils se lancent tous deux dans une série d'aventures, Sophie tentant de se libérer de son mauvais sort. Roman adapté au cinéma par H. Miyazaki sous le titre Le château ambulant. <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur jeunesse; JONE SF <br> <br> Bibliothèque Port Marchand, Secteur jeunesse, JONE R T.01 </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:c5578de6-ed4d-43c7-8bbc-60101b1e8d2b,QueryString:'sorcery%20of%20thorns',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'sorcery%20of%20thorns',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Sorcery of Thorns</a>, Margaret Rogerson</p><img src="https://m.media-amazon.com/images/I/71AuWgN2H7L._UF1000,1000_QL80_.jpg" alt="Sorcery" style="width:100px;"> <p>Peu de temps après le passage du sorcier Nathaniel Thorn à la grande bibliothèque d'Austermeer, l'un des ouvrages se transforme en monstre, semant mort et destruction. Accusée de l'avoir libérée, Elisabeth doit comparaître devant la justice. Prise au coeur d'une conspiration, elle n'a d'autre choix que de se tourner vers Nathaniel et son mystérieux serviteur, Silas. <br> <br> Bibliothèque Sainte Musse, Secteur jeunesse, ROGE R </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'24a2d801-3f2c-473d-a28e-3f5cb332613d',QueryString:'tress%20de%20la%20mer%20emeraude',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'tress%20de%20la%20mer%20emeraude',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))"> Tress de la mer émeraude</a>, Brandon Sanderson</p><img src="https://m.media-amazon.com/images/I/81VELqJKuFL._UF1000,1000_QL80_.jpg" alt="Tress" style="width:100px;"> <p>Tress vit sur une petite île isolée au beau milieu d'un océan... de spores. Simple laveuse de vitres, elle partage néanmoins une belle complicité avec Charlie, le fils du duc, et est secrètement amoureuse de lui. Quand celui-ci disparaît, la jeune femme décide de partir à sa recherche. C'est le début d'un périple au bout du monde, où l'on retrouve tous les ingrédients qui font le sel des grandes aventures : des contrebandiers de la pire espèce, une sorcière malintentionnée, un redoutable dragon, des pirates sales et méchants (ou pas), et même un rat qui parle... <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur adulte; SAND SF <br> <br> Bibliothèque Sainte Musse, Secteur adulte, SAND SF </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:2,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'0f0149ef-bbe5-4293-959d-d5425b12d199',QueryString:'le%20petit%20guide%20de%20miss%20percy',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20petit%20guide%20de%20miss%20percy',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))"> Le petit guide de Miss Percy ou Comment élever un dragon britannique</a>, Quenby Olson </p><img src="https://milady.fr/media/cache/book/07/9782811230807.jpg" alt="Miss Percy" style="width:100px;"> <p>Mildred Percy mène une vie tranquille, jusqu'au jour où son grand-oncle lui lègue un oeuf de dragon. Alors qu'elle élève le petit dragon, elle doit faire face à ses sentiments naissants pour un pasteur. <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur adulte; OLSO SF T.01 </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:5,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:e52b15bf-8b51-4036-ad12-2c89e5f3d1d7,QueryString:'le%20chateau%20de%20hurle',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20chateau%20de%20hurle',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Le château de hurle</a>, Diana Wynne Jones</p><img src="https://m.media-amazon.com/images/I/71yS-KZw9eL._UF1000,1000_QL80_.jpg" alt="Château" style="width:100px;"> <p> Aînée de trois filles, Sophie vit dans un univers où la magie fait partie du quotidien. Maudite par une sorcière et transformée en vieille dame, elle rencontre le magicien Hurle qui habite un château volant. Ils se lancent tous deux dans une série d'aventures, Sophie tentant de se libérer de son mauvais sort. Roman adapté au cinéma par H. Miyazaki sous le titre Le château ambulant. <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur jeunesse; JONE SF <br> <br> Bibliothèque Port Marchand, Secteur jeunesse, JONE R T.01 </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:c5578de6-ed4d-43c7-8bbc-60101b1e8d2b,QueryString:'sorcery%20of%20thorns',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'sorcery%20of%20thorns',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Sorcery of Thorns</a>, Margaret Rogerson</p><img src="https://m.media-amazon.com/images/I/71AuWgN2H7L._UF1000,1000_QL80_.jpg" alt="Sorcery" style="width:100px;"> <p>Peu de temps après le passage du sorcier Nathaniel Thorn à la grande bibliothèque d'Austermeer, l'un des ouvrages se transforme en monstre, semant mort et destruction. Accusée de l'avoir libérée, Elisabeth doit comparaître devant la justice. Prise au coeur d'une conspiration, elle n'a d'autre choix que de se tourner vers Nathaniel et son mystérieux serviteur, Silas. <br> <br> Bibliothèque Sainte Musse, Secteur jeunesse, ROGE R </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'24a2d801-3f2c-473d-a28e-3f5cb332613d',QueryString:'tress%20de%20la%20mer%20emeraude',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'tress%20de%20la%20mer%20emeraude',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))"> Tress de la mer émeraude</a>, Brandon Sanderson</p><img src="https://m.media-amazon.com/images/I/81VELqJKuFL._UF1000,1000_QL80_.jpg" alt="Tress" style="width:100px;"> <p>Tress vit sur une petite île isolée au beau milieu d'un océan... de spores. Simple laveuse de vitres, elle partage néanmoins une belle complicité avec Charlie, le fils du duc, et est secrètement amoureuse de lui. Quand celui-ci disparaît, la jeune femme décide de partir à sa recherche. C'est le début d'un périple au bout du monde, où l'on retrouve tous les ingrédients qui font le sel des grandes aventures : des contrebandiers de la pire espèce, une sorcière malintentionnée, un redoutable dragon, des pirates sales et méchants (ou pas), et même un rat qui parle... <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur adulte; SAND SF <br> <br> Bibliothèque Sainte Musse, Secteur adulte, SAND SF </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:2,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'0f0149ef-bbe5-4293-959d-d5425b12d199',QueryString:'le%20petit%20guide%20de%20miss%20percy',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20petit%20guide%20de%20miss%20percy',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))"> Le petit guide de Miss Percy ou Comment élever un dragon britannique</a>, Quenby Olson </p><img src="https://milady.fr/media/cache/book/07/9782811230807.jpg" alt="Miss Percy" style="width:100px;"> <p>Mildred Percy mène une vie tranquille, jusqu'au jour où son grand-oncle lui lègue un oeuf de dragon. Alors qu'elle élève le petit dragon, elle doit faire face à ses sentiments naissants pour un pasteur. <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur adulte; OLSO SF T.01 </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:5,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:e52b15bf-8b51-4036-ad12-2c89e5f3d1d7,QueryString:'le%20chateau%20de%20hurle',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20chateau%20de%20hurle',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Le château de hurle</a>, Diana Wynne Jones</p><img src="https://m.media-amazon.com/images/I/71yS-KZw9eL._UF1000,1000_QL80_.jpg" alt="Château" style="width:100px;"> <p> Aînée de trois filles, Sophie vit dans un univers où la magie fait partie du quotidien. Maudite par une sorcière et transformée en vieille dame, elle rencontre le magicien Hurle qui habite un château volant. Ils se lancent tous deux dans une série d'aventures, Sophie tentant de se libérer de son mauvais sort. Roman adapté au cinéma par H. Miyazaki sous le titre Le château ambulant. <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur jeunesse; JONE SF <br> <br> Bibliothèque Port Marchand, Secteur jeunesse, JONE R T.01 </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:c5578de6-ed4d-43c7-8bbc-60101b1e8d2b,QueryString:'sorcery%20of%20thorns',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'sorcery%20of%20thorns',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Sorcery of Thorns</a>, Margaret Rogerson</p><img src="https://m.media-amazon.com/images/I/71AuWgN2H7L._UF1000,1000_QL80_.jpg" alt="Sorcery" style="width:100px;"> <p>Peu de temps après le passage du sorcier Nathaniel Thorn à la grande bibliothèque d'Austermeer, l'un des ouvrages se transforme en monstre, semant mort et destruction. Accusée de l'avoir libérée, Elisabeth doit comparaître devant la justice. Prise au coeur d'une conspiration, elle n'a d'autre choix que de se tourner vers Nathaniel et son mystérieux serviteur, Silas. <br> <br> Bibliothèque Sainte Musse, Secteur jeunesse, ROGE R </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'24a2d801-3f2c-473d-a28e-3f5cb332613d',QueryString:'tress%20de%20la%20mer%20emeraude',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'tress%20de%20la%20mer%20emeraude',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))"> Tress de la mer émeraude</a>, Brandon Sanderson</p><img src="https://m.media-amazon.com/images/I/81VELqJKuFL._UF1000,1000_QL80_.jpg" alt="Tress" style="width:100px;"> <p>Tress vit sur une petite île isolée au beau milieu d'un océan... de spores. Simple laveuse de vitres, elle partage néanmoins une belle complicité avec Charlie, le fils du duc, et est secrètement amoureuse de lui. Quand celui-ci disparaît, la jeune femme décide de partir à sa recherche. C'est le début d'un périple au bout du monde, où l'on retrouve tous les ingrédients qui font le sel des grandes aventures : des contrebandiers de la pire espèce, une sorcière malintentionnée, un redoutable dragon, des pirates sales et méchants (ou pas), et même un rat qui parle... <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur adulte; SAND SF <br> <br> Bibliothèque Sainte Musse, Secteur adulte, SAND SF </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:2,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'0f0149ef-bbe5-4293-959d-d5425b12d199',QueryString:'le%20petit%20guide%20de%20miss%20percy',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20petit%20guide%20de%20miss%20percy',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))"> Le petit guide de Miss Percy ou Comment élever un dragon britannique</a>, Quenby Olson </p><img src="https://milady.fr/media/cache/book/07/9782811230807.jpg" alt="Miss Percy" style="width:100px;"> <p>Mildred Percy mène une vie tranquille, jusqu'au jour où son grand-oncle lui lègue un oeuf de dragon. Alors qu'elle élève le petit dragon, elle doit faire face à ses sentiments naissants pour un pasteur. <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur adulte; OLSO SF T.01 </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:5,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:e52b15bf-8b51-4036-ad12-2c89e5f3d1d7,QueryString:'le%20chateau%20de%20hurle',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20chateau%20de%20hurle',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Le château de hurle</a>, Diana Wynne Jones</p><img src="https://m.media-amazon.com/images/I/71yS-KZw9eL._UF1000,1000_QL80_.jpg" alt="Château" style="width:100px;"> <p> Aînée de trois filles, Sophie vit dans un univers où la magie fait partie du quotidien. Maudite par une sorcière et transformée en vieille dame, elle rencontre le magicien Hurle qui habite un château volant. Ils se lancent tous deux dans une série d'aventures, Sophie tentant de se libérer de son mauvais sort. Roman adapté au cinéma par H. Miyazaki sous le titre Le château ambulant. <br> <br> Bibliothèque Chalucet, étage 1-Fiction, Secteur jeunesse; JONE SF <br> <br> Bibliothèque Port Marchand, Secteur jeunesse, JONE R T.01 </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=tress+de+la+mer+emeraude&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:c5578de6-ed4d-43c7-8bbc-60101b1e8d2b,QueryString:'sorcery%20of%20thorns',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'sorcery%20of%20thorns',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Sorcery of Thorns</a>, Margaret Rogerson</p><img src="https://m.media-amazon.com/images/I/71AuWgN2H7L._UF1000,1000_QL80_.jpg" alt="Sorcery" style="width:100px;"> <p>Peu de temps après le passage du sorcier Nathaniel Thorn à la grande bibliothèque d'Austermeer, l'un des ouvrages se transforme en monstre, semant mort et destruction. Accusée de l'avoir libérée, Elisabeth doit comparaître devant la justice. Prise au coeur d'une conspiration, elle n'a d'autre choix que de se tourner vers Nathaniel et son mystérieux serviteur, Silas. <br> <br> Bibliothèque Sainte Musse, Secteur jeunesse, ROGE R </p> `,
];

const backgrounds = [
  'url("https://img.freepik.com/vecteurs-libre/modele-art-deco-premium-design-plat_23-2149150038.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-premium/motif-floral-geometrique-design-abstrait-bleu-marine-or_1253114-46448.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/modele-conception-scandinave-plat_23-2148952197.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/modele-conception-scandinave-plat_23-2148948136.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/art-voronoi-est-structure-blocs-abstraite-motif-conception-arriere-plan_1017-54631.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/photos-gratuite/conception-abstraite-motifs-sans-couture_23-2151179082.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/foto-gratis/diseno-patrones-costuras-abstractos_23-2151179214.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/photos-gratuite/conception-motifs-abstraits-sans-couture_23-2151179083.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/photos-gratuite/conception-abstraite-motifs-sans-couture_23-2151179066.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/conception-modele-mosaique-geometrique-plat_23-2149286388.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/fond-motif-geometrique-design-plat_23-2149924295.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/motif-lignes-aquarelle-abstraite_23-2149203335.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/motif-geometrique-plat-boho_23-2149762191.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/free-vector/flat-scandinavian-design-pattern_23-2148948919.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/free-vector/flat-design-scandinavian-design-pattern_23-2148936070.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/modele-renouvellement-retro-dessine-main_23-2149737394.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-premium/feuilles-botaniques-abstraites-colorees-vecteur-modele-sans-couture-petits-points-illustration-design-pour-mode-tissu-textile-papier-peint-couverture-web-emballage-toutes-impressions-blanc_44285-2032.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/photos-premium/gros-plan-motif-feuilles-forme-eventail-fond-noir-ai-generative_955925-60248.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/photos-gratuite/conception-abstraite-motifs-sans-couture_23-2151179225.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/damasse-sans-soudure-fond_1217-847.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/damasse-sans-soudure-fond_1217-1341.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/arriere-plan-ornemental-floral-dore_23-2148437704.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/photos-premium/motif-notes-musique-papier-peint_916191-380657.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/modele-conception-scandinave-plat_23-2148950515.jpg?semt=ais_hybrid&w=740&q=80")'
];

const calendar = document.getElementById('calendar');

// 1. Créer un tableau [0, 1, 2, ..., 23] pour les indices
const indices = Array.from(Array(24).keys());

// 2. Mélanger les indices avec l'algorithme de Fisher-Yates
for (let i = indices.length - 1; i > 0; i--) {
  const j = Math.floor(Math.random() * (i + 1));
  [indices[i], indices[j]] = [indices[j], indices[i]];
}

// 3. Créer les cases dans l’ordre mélangé
indices.forEach(index => {
  const day = document.createElement('div');
  day.classList.add('day');

  const numberSpan = document.createElement('span');
  numberSpan.classList.add('day-number');
  numberSpan.textContent = index + 1;
  day.appendChild(numberSpan);

  day.setAttribute('data-message', messages[index]);

  // ✅ Appliquer le fond à motif ici
const bg = backgrounds[index % backgrounds.length];
  console.log(`Index: ${index}, Background: ${bg}`); // Ajout pour debug  
  day.style.backgroundImage = bg;
  day.style.backgroundSize = 'cover';
  day.style.backgroundPosition = 'center';
  day.style.backgroundRepeat = 'no-repeat';

 // Ajouter l'événement de clic avec contrôle sur la date
  day.addEventListener('click', function () {
    const now = new Date();
    const today = now.getDate();
    const currentMonth = now.getMonth() + 1; // mois de 1 à 12
    const dayNumber = parseInt(this.querySelector('.day-number').textContent);

    if (currentMonth === 10) {
      if (dayNumber <= today) {
        this.classList.add('opened');
        const modal = document.getElementById('modal');
        const modalMessage = document.getElementById('modal-message');
        modalMessage.innerHTML = this.getAttribute('data-message');
        modal.style.display = 'flex';
      } else {
        alert("Cette case ne peut pas encore être ouverte !");
      }
    } else {
      alert("Le calendrier est disponible uniquement en décembre !");
    }
  });

  calendar.appendChild(day);
});


// 4. Ajouter la case logo à la fin
const logoBox = document.createElement('div');
logoBox.classList.add('day', 'empty');

const logoImg = document.createElement('img');
logoImg.src = "https://provence-med.media.tourinsoft.eu/upload/30655909-9f4152bcb0114836848fa1dfd0fc4b5d.jpg";
logoImg.alt = "Logo";
logoImg.style.width = "100px";
logoImg.style.height = "auto";

logoBox.appendChild(logoImg);
calendar.appendChild(logoBox);

// Fermeture de la modale
const closeButton = document.querySelector('.close-button');
const modal = document.getElementById('modal');

closeButton.addEventListener('click', function () {
  modal.style.display = 'none';
});

// (optionnel) Fermer la modale en cliquant en dehors du contenu
window.addEventListener('click', function (event) {
  if (event.target === modal) {
    modal.style.display = 'none';
  }
});

