const messages = [
  `<p> <a href="https://mediatheques.toulon.fr/TOULON/doc/SYRACUSE/2109622/rousseau-botaniste-je-vais-devenir-plante-moi-meme-recueil-d-articles-et-catalogue-d-exposition-muse"> Rousseau botaniste : je vais devenir plante moi-même</a>, Claire Jacquier</p><img src="https://images.epagine.fr/330/9782884192330_1_75.jpg" alt="Rousseau" style="width:100px;"> <p>Ce livre, superbement illustré, fait apparaître au fil des pages et des illustrations annotées, la relation intime et passionnée d'un homme conquis depuis l'enfance par le spectacle de la nature. En effet, Rousseau s'est pris de passion pour la botanique et se consacre à la réalisation d'herbiers pour des personnes de sa connaissance, échange avec le naturaliste Carl von Linné… <br> <br> On y apprend, entre autres merveilles, que la plante "préférée" du philosophe était sans doute le Myosotis scorpioides ou myosotis des marais, dont la fleur est souvent d'un bleu couleur de ciel… <br> <br>  MEURET Christophe </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/TOULON/doc/SYRACUSE/2036689/azur-asphalte-sylvain-bordesoules">Azur Asphalte</a>, Sylvain Bordesoules</p><img src="https://media.groupe.gallimard.fr/couvHD/J04573.jpg" alt="vie" style="width:100px;"> <p> Ce que j'ai adoré dans cette BD, c'est la réussite du scénariste à faire partager au lecteur le quotidien de deux femmes (ses deux soeurs) qui tentent chaque jour de construire leur vie le mieux possible tout en faisant courageusement face aux multiples aléas de l'existence. <br> <br> C'est un angle assez novateur qui permet de créer une intimité avec ces personnages très attachantes et si proches de nous ! <br> <br> REYNAUD Aurélia</p> `,
  `<p> <a href="https://mediatheques.toulon.fr/TOULON/search.aspx?SC=DEFAULT&QUERY=Authority_id_idx%3a22230+AND+sys_base%3a%22SYRACUSE%22&QUERY_LABEL=Laurens%2c+Camille+(1957-....).+Auteur#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:12,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:a4a6faef-bbb0-43d3-b974-ecee3cbcc509,QueryString:'Authority_id_idx:22230%20AND%20sys_base:%22SYRACUSE%22',ResultSize:10,ScenarioCode:DEFAULT,ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'Laurens,%20Camille%20(1957-....).%20Auteur',SearchTerms:'Authority_id_idx:22230%20AND%20sys_base:%22SYRACUSE%22',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Ta promesse</a>, Camille Laurens</p><img src="https://images.epagine.fr/238/9782072912238_1_75.jpg" alt="promesse" style="width:100px;"> <p> La romancière Claire Lancel est accusée d'avoir frappé à la tête son ex-compagnon, Gilles Fabian, un metteur en scène spécialisé dans le théâtre de marionnettes qui se trouve depuis dans le coma. A travers des entretiens avec son avocate, qui cherche à reconstituer le déroulé des événements, Claire évoque les différentes étapes qui l'ont amenée à commettre ce geste criminel. <br> <br> BRIS CHRISTINE </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=affaire+Nevenka&QUERY_LABEL=#/Search/(query:(InitialSearch:!t,Page:0,PageRange:3,QueryString:'affaire%20Nevenka',ResultSize:-1,ScenarioCode:'CATA%20TOUL',SearchContext:0,SearchLabel:''))"> L’affaire Nevenka</a>,  Icíar Bollaín </p><img src="https://fr.web.img6.acsta.net/img/32/88/3288a42d9225f3c6740d82fb2c465dfb.jpg" alt="Nevenka" style="width:100px;"> <p> 1999, en Espagne. L’histoire (vraie) d’une jeune femme, Nevenka Fernández, élue à un conseil municipal, protégée du maire, puis sa nouvelle conquête et, dès lors qu’elle tenta d’échapper à son emprise, sa proie sans défense. <br> <br> Mais alors qu’aucune femme n’avait jamais osé le faire, la fragile Nevenka finira par dénoncer les violences subies, ce qui aboutira à un procès retentissant et inédit dans le monde politique espagnol. Un film qui illustre très bien les ressorts du patriarcat et qui s’engage en faveur de la réparation des femmes meurtries. <br> <br> Sébastien </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=Roman+Policier%2C+Philibert+Humm+&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:9,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'8afb1423-b3e9-479e-9e48-da505e131dc7',QueryString:'tout%20le%20monde%20aime%20clara',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'tout%20le%20monde%20aime%20clara',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Tout le monde aime Clara</a>, David Foenkinos</p><img src="https://static.fnac-static.com/multimedia/PE/Images/FR/NR/7e/c4/1a/18531454/1507-1/tsp20250403075843/Tout-le-monde-aime-Clara.jpg" alt="voyance" style="width:100px;"> <p> A la suite d'un accident de voiture, Clara 16 ans est plongée dans le coma pendant 8 mois. Malgré cette tragédie, cette famille va se rapprocher et s'unir pour toujours. A son réveil, Clara est différente, elle se retrouve avec un don de "voyance" ce qui va lui permettre de redonner vie à un être éteint!!! <br> <br> C'est un roman intense est touchant et vivifiant à la fois. Le thème de la "voyance" après un traumatisme cérébral est très bien imaginé et développé. <br> <br> A lire absolument!!! <br> <br> Christine </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=Roman+Policier%2C+Philibert+Humm+&QUERY_LABEL=#/Detail/(query:(Id:'2_OFFSET_0',Index:3,NBResults:7,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'4de76b9e-ccf0-4960-bfc9-a1bc7c4f8f88',QueryString:'rainbow%20george%20abe',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'rainbow%20george%20abe',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Rainbow</a>, George Abe & Masasumi Kakizaki</p><img src="https://m.media-amazon.com/images/I/51eUrnv5zAL._AC_UF1000,1000_QL80_.jpg" alt="mot" style="width:100px;"> <p> Rainbow est un seinen manga écrit par George Abe et dessiné par Masasumi Kakizaki qui raconte l'histoire de sept adolescents qui se retrouvent dans une même cellule dans la maison de redressement de Shonan. On est au Japon dans l'après-guerre. <br> <br>Cette histoire bouleversante de ces jeunes laissés pour compte met l'accent sur les liens de fraternité et de solidarité qui naissent entre des individus pour faire face à l'adversité alors qu'ils subissent de mauvais traitements.<br> <br>Cette ode à la liberté prend aux  tripes, elle n'épargne pas le lecteur qui éprouve alors une véritable empathie pour ces personnages malmenés par la vie mais dont le courage force le respect. Une grande leçon d'humanité.<br>Voilà un manga que vous n'êtes pas prêt d'oublier! <br> <br> Stéphane </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=Roman+Policier%2C+Philibert+Humm+&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:d1137f29-1d09-47cf-b6b3-a925e133cda3,QueryString:'Les%20%C3%A9l%C3%A9ments%20/%20John%20Boyne',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'Les%20%C3%A9l%C3%A9ments%20/%20John%20Boyne',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Les élements</a>, John Boyne</p><img src="https://www.pagedeslibraires.fr/images/livre/9782709674300/9782709674300-couv.jpg" alt="éléments" style="width:100px;"> <p> Cet ouvrage, récompensé par le prix Roman Fnac 2025, aborde des thèmes profonds tels que le deuil, l’identité et la reconstruction après un traumatisme vécu dans l’enfance.<br> Nous suivons tour à tour quatre personnages, chacun ayant traversé des épreuves traumatisantes. Chaque protagoniste est le personnage central d’une des quatre parties du livre et est symbolisé par un élément. Le récit se déroule à un moment charnière de leur vie. Certains trouveront la résilience, tandis que pour d’autres, ce sera le cercle vicieux de la violence. <br> <br>Les destins de ces personnages vont se croiser avec des rencontres parfois salvatrices, parfois fatales… L’auteur nous prend à contre-pied et nous surprend avec des stratégies extrêmement efficaces. Les personnages ont des caractères complexes et très attachants pour certains. <br>J’ai dévoré ce roman captivant, dont la lecture s’est révélée véritablement addictive. C’est sans conteste un ouvrage incontournable de cette rentrée littéraire ! <br> <br> Marion </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=un+fruit+rouge&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:26,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:f375046c-a24d-4033-8ee4-48e437165685,QueryString:'un%20fruit%20rouge',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'un%20fruit%20rouge',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Un fruit rouge</a>, Yi Gee Eun</p><img src="https://static.fnac-static.com/multimedia/PE/Images/FR/NR/a6/f1/a9/11137446/1507-1/tsp20231201081204/Un-fruit-rouge.jpg" alt="fruit" style="width:100px;"> <p> Ce bel album d'une artiste coréenne raconte l'histoire d'un petit ours affamé qui n'hésite pas à entamer l'ascension d'un arbre pour attraper une baie couleur rouge qui s'avère être... un écureuil ou encore le soleil. Avec ses illustrations douces en noir et blanc, avec seulement une touche de couleur . <br><br>C'est tendre, d'une élégante simplicité avec un sens artistique indéniable : touches de couleurs, beautés des lignes des troncs d'arbres, découpage, quête pour l'ourson... qui feront poser des questions au jeune enfant et savourer ce qui se trouve autour de lui<br> <br> Palazy Dominique  </p> `,
  `<p> Place Armand Vallé - Station des Autobus Toulon – Intérieur de la Gare P.L.M. </p><img src="cartes.png" alt="mot" style="width:200px;"> <p> Documents consultables sur RDV à la <a href="https://mediatheques.toulon.fr/TOULON/~~/fonds-particuliers.aspx" >Réserve de Lagoubran </a> <br> <br> Ces cartes postales font partie d’une collection de près de 3 000 cartes postales anciennes de Toulon et de ses environs.  Récoltées par le Club Cartophile Toulonnais pendant des années et conservées par la Bibliothèque de Toulon depuis 1995, ces cartes du début du XXème siècle sont progressivement numérisées pour être exposées, consultées et utilisées plus facilement ! <br> <br> Aujourd’hui, c’est le jeu des 7 différences, mais pour corser un peu la chose, c’est aussi celui des 7 ressemblances ! C’est ce qui est formidable avec les cartes postales anciennes. Elles nous font (re)découvrir des lieux, des rues ou des places. Elles nous permettent de rencontrer d’autres modes de vie, qui n’existent plus ou qui au contraire perdurent. La magie, c’est que plus on les observe, plus on aperçoit de nouveaux détails : pour certains différents, pour d’autres similaires et pour la plupart, un peu entre les deux…   <br> <br> Emilie  </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/TOULON/doc/SYRACUSE/2017677/mythologie-du-12-celestin-de-meeus">Mythologie du .12</a>, Célestin De Meeûs</p><img src="https://img.rts.ch/articles/2024/image/vxcnds-28609059.image?w=640&h=640" alt="mythologie" style="width:130px;"> <p> Encore un roman édité aux éditions du Sous-Sol qui mérite le détour. Ce n’est pas un titre très récent : en novembre 2024, j’avais adoré lire à voix haute les premières pages de Mythologie du .12 dans un même souffle (la scène d’ouverture se passe sur un parking, et elle se déploie sur plusieurs pages dans une seule et même phrase), lors d’un “Jeudi, je lis” consacré à la rentrée littéraire. <br> <br>J’ai attendu un an pour reprendre le récit et le lire en entier ... Même choc ressenti que pour le primé Aliène de Phoebe Hadjimarkos Clark : ces romans sont pour moi des cousins ! Ils sont portés par une tension narrative similaire et j’ai l’impression qu’ils explorent, chacun à leur façon, les mêmes émotions (la violence et la peur) ainsi que des thèmes voisins (l’aliénation, le sentiment d’appartenance à la communauté humaine), avec un personnage central non humain en commun : la forêt, sans parler des pétards fumés en route ... <br> <br> J’ai trouvé l’écriture de Célestin de Meeûs absolument virtuose dans sa manière d’entrelacer les récits et de manier les styles de langue, avec un mélange incongru d’extrême familiarité juxtaposée à une forme plus soutenue de précision chirurgicale – ou plutôt botanique  –   dans les descriptions de la forêt.<br> <br> Sarah Guegache </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=comme+en+amour&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:959,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'401e1bb0-aa20-42e3-9fc5-43d0a7eae0ff',QueryString:'comme%20en%20amour',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'comme%20en%20amour',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Comme en amour</a>, Alice Ferney</p><img src="https://rentree.actes-sud.fr/wp-content/uploads/2025/06/9782330209254_couv_300_ok.jpg" alt="amour" style="width:100px;"> <p>L’amitié entre un homme et une femme est le thème du nouveau roman d’Alice Ferney. Ce lien subtil, ténu, nourricier, peut devenir pesant et dérangeant. Ce sont toutes les nuances et les limites d’une relation amicale qu’explore ce roman. Doit-on tout se dire ? Quels sont les enjeux de cette relation pour les protagonistes ? Rompt-on en amitié comme on rompt en amour ? J’ai adoré le style de l’autrice, dynamisé par de courts chapitres et de nombreux dialogues. C’est avec finesse et beaucoup de talent qu’elle décrypte les sentiments et les émotions de ses personnages. Un gros coup de cœur et une idée de cadeau à offrir pour Noël à un.e ami.e !  <br> <br> Delphine THIRIET </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=Nous+n%27avons+rien+a+envier+au+reste+du+monde+&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(CloudTerms:!(),FacetFilter:%7B%7D,ForceSearch:!t,InitialSearch:!f,ListSelectionPage:!(0),Page:0,PageRange:3,QueryGuid:'15a7d146-c2d0-48c5-bcff-dbbc8817b36c',QueryString:'Le%20Fin%20Chemin%20des%20anges%20Simon%20Johannin',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'Le%20Fin%20Chemin%20des%20anges%20Simon%20Johannin',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Le fin chemin des anges</a>, Simon Johannin</p><img src="https://www.denoel.fr/system/files/styles/medium/private/migrations/ouvrages/couvertures/B27241.jpg.webp?itok=tS9EnOY0" alt="condamne" style="width:100px;"> <p> L'auteur et poète d'à peine 32 ans, nous offre un récit poignant et poétique.<br> <br> Nous suivons le récit de Louis, jeune garçon condamné pour un menu larcin au XIXème siècle, et envoyé dans au bagne pour mineurs sur l'île du Levant en 1866.L'écriture est élégante, la lecture captivante et émouvante.<br> <br> Corinne COURTEAU </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/TOULON/doc/SYRACUSE/335989/le-gout-de-la-cerise-abbas-kiarostami-real">Le goût de la cerise</a>, Abbas Kiarostami</p><img src="https://medias.boutique.lab.arte.tv/prod/29262_vod_thumb_156534.jpg" alt="perse" style="width:100px;"> <p> M. Badii va mal. Dans le monde réel, il consulterait un psy, se ferait prescrire un antidépresseur et l'histoire s'arrêterait là. Mais nous sommes au cinéma, où les conventions sociales s’abolissent, et M. Badii arpente obstinément les faubourgs de Téhéran à bord de son 4x4, en quête d'un exécuteur testamentaire d’un genre un peu particulier (il est presque impossible de s'inhumer soi-même, ceux qui ont essayé pourront en témoigner). Les motivations de M. Badii, que son appartenance à la bonne société téhéranaise semble protéger des soucis matériels, nous demeureront obscures. <br> <br> Nous voilà déjà loin de "l’esprit de Noël" et de l’idée qu’on se fait généralement d’un divertissement familial, mais le film, imprégné de l’esprit d’Omar Khayam et parfois teinté d’une pointe d’humour persan, n’apparait pas aussi désespéré que son anti-héros. Kiarostami, sans prendre parti, nous propose un apologue (comment ne pas évoquer également le Livre de Job ?) dans lequel chacun des interlocuteurs de M. Badi délivre sa part de vérité, souvent plus dérisoire que consolante.  Aujourd’hui qu’acteur et réalisateur sont morts, l’épilogue, lambeau de making-of censé nous rappeler que ce qui a précédé n'était "que" du cinéma, revêt une dimension quasi spectrale. Mais le regard de M. Badii nous habitera encore longtemps.<br> <br> Nicolas  </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/TOULON/doc/SYRACUSE/2033999/she-is-beautiful-1-scenario-jun-esaka">She is beautiful </a>, Jun Esaka</p><img src="https://m.media-amazon.com/images/I/61tRRzY7kiL.jpg" alt="beautiful" style="width:100px;"> <p> Kurumi est une jeune fille de 9 ans (presque 10), elle vit dans "L'enclos". Un lieu bien mystérieux où ne vivent apparemment que des femmes. À leur dixième anniversaire, une affectation à l'un des quatre métiers possibles leur est imposée. Mais voilà qu'un matin, Kurumi se réveille hors de "L'enclos"... et surtout quatorze ans ont passé et elle n'en a aucun souvenir. <br> <br> J'ai été happée dès le début par ce premier tome : il est rythmé, bien construit et lance les premières pistes d'une intrigue complexe sur un monde dystopique. Cela faisait bien longtemps que je n'avais pas été aussi convaincue et conquise par un manga. Autre point positif, la série est courte et terminée en 6 tomes. <br> <br> Carole G. </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=le+trait%C3%A9+du+citronier&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:af3454e1-5ad5-4b68-8607-46e3d0a011cc,QueryString:'le%20trait%C3%A9%20du%20citronier',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'le%20trait%C3%A9%20du%20citronier',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">  Le Traité du Citronier</a>, Etienne Michel </p><img src="https://i.pinimg.com/736x/39/b4/d7/39b4d7271c88fe55ee69145a5b9cda25.jpg" alt="citron" style="width:100px;"> <p>Magnifique ouvrage de botanique rédigé et édité par Etienne Michel en 1816. Toutes les planches sont dessinées d’après nature par Pancrace Bessa, peintre de fleurs et de sciences naturelles. <br> <br>Ce traité décrit chaque espèce de citrons dans de courtes notices et présente 21 planches gravées rehaussées de couleurs chatoyantes. Un régal à consulter par les amateurs d’agrumes dans les fonds anciens de la bibliothèque. <br> <br> Véronique</p> `,
  `<p> <a href="https://mediatheques.toulon.fr/TOULON/doc/SYRACUSE/2130379/je-voulais-vivre-milady-n-est-pas-une-femme-qui-pleure-elle-est-de-celles-qui-se-vengent-adelaide-de">Je voulais vivre</a>, Adelaïde de Clermont-Tonnerre </p><img src="https://m.media-amazon.com/images/I/71n03VNoZGL._AC_UF1000,1000_QL80_.jpg" alt="vivre" style="width:100px;"> <p> Ce roman nous raconte l’histoire de Milady, la femme fatale qui, chez Alexandre Dumas et dans la littérature, incarne perversion et beauté envoûtante, mais est ici réinterprétée sous un angle inédit : celui de Milady elle-même, et, cette perspective change tout ! <br> <br>Il ne s’agit pas d’une simple réécriture des événements auxquels Milady fait face dans Les Trois Mousquetaires, l’autrice ne modifie pas le cours des actions ni ne cherche à absoudre Milady de ses actes répréhensibles. Au contraire, elle propose un nouveau regard, et cela fonctionne à merveille ! <br> Nous nous retrouvons dans sa tête, dans sa chair et on reste un peu étonné car, non, nous ne l’avions pas vu sous cet angle. Nous avons aussi détesté, jugé et condamné cette femme, qui n’avait souvent d’autre choix que de se défendre comme elle le faisait car elle refusait de se plier aux attentes de son époque et aspirait à la liberté.  <br> <br> Avec brio l’autrice se glisse dans les interstices laissés par Dumas pour développer ce personnage, elle lui donne une histoire, la réhabilite, lui rend justice. Je voulais vivre est mon grand coup de cœur de la rentrée littéraire. <br> <br> Marion</p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=les+soeurs+carmine&QUERY_LABEL=#/Detail/(query:(Id:'1_OFFSET_0',Index:2,NBResults:3,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'1dac6417-83fa-40ae-a6e5-de397b62da9a',QueryString:'les%20soeurs%20carmine',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'les%20soeurs%20carmine',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Les soeurs Carmines</a>, Ariel Holzl</p><img src="https://m.media-amazon.com/images/I/81WnfREkI5L._AC_UF1000,1000_QL80_.jpg" alt="corbeau" style="width:100px;"> <p> Pour un humour burlesque au possible, des personnages déroutants mais attachants et une ambiance macabre, je ne peux que vous conseiller Les sœurs Carmine. Vous suivrez, dans le premier tome, Merry, la cadette de la famille qui, pour maintenir sa famille à flot (cette dernière étant fauchée comme les blés) se retrouve à réaliser de nombreux vols. <br> <br>  Le comble étant qu’elle a une fâcheuse tendance à rater ses missions. Et que, ni son ainée (l’hautaine et égoïste, mais au combien attachante Tristabelle) ni sa benjamine (la petite et naïve Dolorine) ne semblent disposées à l’aider. <br> <br>  Vous hésitez encore ? Peut-être que la devise de Grisaille (la ville de residence de nos héroïnes) saura vous convaincre : « Quid non occiderem occidisti primum », « Ce qui ne vous tue pas est ce que vous avez tué en premier » <br> <br> Chloé </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=james+Percival+Everett+&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:2,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'7904c48d-7e44-4a53-af35-0a9ca0a52bf7',QueryString:'james%20Percival%20Everett%20',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'james%20Percival%20Everett%20',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">James</a>, Percival Everett </p><img src="https://static.fnac-static.com/multimedia/PE/Images/FR/NR/cd/5a/21/18963149/1507-1/tsp20250825075052/James.jpg" alt="esclavage" style="width:100px;"> <p> Je ne peux que vous recommander la lecture du roman de Percival Everett lauréat du Prix Pulitzer 2025. Le récit débute à la veille de la guerre de Sécession et met en scène le personnage de James ainsi que celui de Huck. Le premier est un esclave qui décide de s’enfuir afin de récolter suffisamment d’argent pour racheter son épouse et sa fille. L’auteur nous livre un récit poignant sur les conditions de vie des esclaves à cette époque et un réquisitoire contre les mauvais traitements dont la population noire était victime. Battus, fouettés, pendus, violées telle était la condition des esclaves sous la direction de propriétaires blancs sans scrupules ni états d’âme. <br> <br> La tension monte crescendo jusqu’à un dénouement palpitant auquel on ne s’attendait pas du tout. Le récit est d’autant plus passionnant que le personnage de James converse avec les philosophes des Lumières comme Voltaire et Locke sur l’ambiguïté de leur pensée sur l’esclavage. Au cours de son périple, il va faire de nombreuses rencontres parfois au péril de sa vie. Voilà une réappropriation du roman de Mark Twain qu’il faut absolument avoir lue <br> <br> Stéphane </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/TOULON/search.aspx#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:75,PageRange:3,SearchQuery:(CloudTerms:!(),ExceptTotalFacet:!t,FacetFilter:%7B%7D,ForceSearch:!t,HiddenFacetFilter:%7B%7D,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'0c73ee5d-f896-45b2-8fb1-2e6d22f32517',QueryString:'les%20maisons%20imaginaires',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'les%20maisons%20imaginaires',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Les maisons imaginaires</a>, Anne Montel</p><img src="https://m.media-amazon.com/images/I/717C0KNCjYL._AC_UF1000,1000_QL80_.jpg" alt="maisons" style="width:100px;"> <p>  Visite insolite 5/5  Après Les Restaurants Imaginaires et l’Abécédaire des Métiers Imaginaires, Anne Montel fait un grand retour avec un nouvel opus de cette collection : Les Maisons Imaginaires. <br> Dès la couverture à découpe, c' est une véritable invitation au voyage, à la rêverie et à la poésie qui s' offre à nous : Comme si nous étions acteurs du livre, car nous voulons voir ce qui se cache derrière cette lucarne, d' où un petit côté voyeuriste. Ce livre atypique (livre objet) nous laisse entrapercevoir un monde merveilleux et nous donne envie d' aller plus loin. <br> <br> Le travail de l' éditeur Little Urban est très soigné : Mors et dos du livre tout de toile vêtu, lettres du titre scintillantes : comme si le livre avait revêtu sa plus belle parure et s' apprêtait à festoyer. A chaque double page du livre c' est tout un petit monde qui s' offre à nous : livre à flaps, une illustration peut en cacher une autre ! Détournements d' objets (le réveil se transforme en maison), focus sur les petits insectes : les pages grouillent de détails, les petites bestioles sont personnifiées : Tout est beau savoureux et drôle ! Un livre tout en poésie à visiter sans modération ! <br> <br> GEHIN </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/TOULON/doc/SYRACUSE/1684518/quelqu-un-m-attend-derriere-la-neige-timothee-de-fombelle">Quelqu'un m'attend derrière la neige</a>, Timothée de Fombelle</p><img src="https://media.groupe.gallimard.fr/couvHD/J00816.jpg" alt="hirondelle" style="width:100px;"> <p> Une nuit de Noël pas comme les autres  <br> <br> 4 étoiles <br> <br> Une hirondelle prénommée Gloria s'entête à voler vers le nord et l'hiver au lieu de rejoindre les températures plus clémentes de l'Afrique. Freddy, un livreur de glaces, solitaire et désenchanté est sommé d'interrompre sa livraison vers Londres et de rentrer chez lui en cette nuit de Noël. Un troisième personnage invisible fait le lien entre ces deux personnages et continents. <br> <br>Thimothée de Fombelle auteur reconnu et talentueux pour ses romans jeunesse livre ici un conte de Noël où se mêle à la fois le charme de cette période festive et des thème contemporains tels que la solitude ou l’exil. Son récit s’enrichit d’illustrations évocatrices, d’une touche de lyrisme et de cette finesse narrative qui signe son style. Une mélancolie subtile traverse ce petit album carré, avant de s’achever sur une lueur d’espoir. Les dessins, baignés de nuit et de neige, jouent des ombres pour révéler la complexité du monde, en parfaite harmonie avec l’histoire. <br>A découvrir absolument ! <br> <br> Seraphine </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=bloomstone+manor&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:1,PageRange:3,SearchQuery:(FacetFilter:'%7B%22_335%22:%22M%C3%A9diath%C3%A8que%20la%20Roseraie%22%7D',ForceSearch:!t,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'3db2255a-7068-4eab-9a1f-480c0c902dac',QueryString:'bloomstone%20manor',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'bloomstone%20manor',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Sous les étoiles de Bloomstone Manor</a>, Mary Orchard</p><img src="https://m.media-amazon.com/images/I/918CYnBtXTL._UF1000,1000_QL80_.jpg" alt="manoir" style="width:100px;"> <p> Fin du XIXème siècle, Londres, sa campagne, Agathe, son désir de s’affranchir du milieu familial conventionnel, la rencontre de leur excentrique voisin et surtout la vie à Bloomstone Manor. J’ai adoré vivre avec tous ses habitants le temps du roman. <br> <br> Valérie TORRES </p> `,
  `<p> <a href=https://mediatheques.toulon.fr/TOULON/search.aspx?SC=CATA+TOUL&QUERY=Titreserie461t_idx%3a%22La+Petite+mort%22&QUERY_LABEL=Recherche+sur+La+Petite+mort#/Detail/(query:(Id:'2_OFFSET_0',Index:3,NBResults:8,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:a1d6cde9-e6b8-43b6-9bcb-0166b105f55e,QueryString:'Titreserie461t_idx:%22La%20Petite%20mort%22',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'Recherche%20sur%20La%20Petite%20mort',SearchTerms:'Titreserie461t_idx:%22La%20Petite%20mort%22',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">La petite mort</a>, Davy Mourier</p><img src="https://www.editions-delcourt.fr/sites/default/files/product/9782756042565-X.jpg" alt="mort" style="width:100px;"> <p> Bientôt Noël! Venez passer un moment chaleureux tout en dégradés de noir auprès de cette Petite Mort touchante à souhait, enfant de la grande Faucheuse. Petite mort est destinée à reprendre le flambeau de papa, mais Petite Mort rêve de devenir fleuriste... Amis de l'humour noir, adeptes de naïveté acidulée, prenez le risque de plonger pour une immersion mortellement cocasse dans l'univers de cette BD savoureuse ! Et joyeux Noël! <br> <br> Agnès CERDAN </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=pomelo+la+grande+aventure&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:2,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'2ba00346-a846-461f-86f8-aa23319c2154',QueryString:'pomelo%20la%20grande%20aventure',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'pomelo%20la%20grande%20aventure',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">Pomelo et la grande aventure</a>, Benjamin Chaud et Ramona Badescu</p><img src="https://m.media-amazon.com/images/I/71+-cn73u3L._AC_UF1000,1000_QL80_.jpg" alt="pomelo" style="width:100px;"> <p> Quand notre monde devient un peu trop étroit, que nous avons fait le tour de notre petit bocal, Il arrive fatalement qu’une envie subite d’aventure s’empare de nous, un besoin irrépressible d’aller voir si les pissenlits ne sont pas plus ébouriffés ailleurs. Alors, pour Pomelo, petit éléphanteau tout choupinou, l’heure du départ a sonné. Le baluchon rempli de victuailles posé sur son épaule, il s’élance vers l’infini et bien au-delà. <br> <br>Son chemin sera semé d’embûches, de rencontres imprévues et de découvertes inattendues. Il découvrira le monde hors des limites de sa vue, là où les étoiles un peu trop solitaires étreignent les océans. Et quand la fatigue s’emparera de Pomelo, la mine triste, perdu dans l’immensité de l’univers, alors il saura que Papamelo et Mamamelo veillent sur lui, que peu importe la destination, il ne marchera jamais seul. <br> <br> Guilhem  </p> `,
  `<p> <a href="https://mediatheques.toulon.fr/search.aspx?SC=CATA+TOUL&QUERY=la+bonne+m%C3%A8re&QUERY_LABEL=#/Detail/(query:(Id:'0_OFFSET_0',Index:1,NBResults:451,PageRange:3,SearchQuery:(FacetFilter:%7B%7D,ForceSearch:!f,InitialSearch:!f,Page:0,PageRange:3,QueryGuid:'6c529873-a120-4f8e-85b0-19cc63c57c50',QueryString:'la%20bonne%20m%C3%A8re',ResultSize:10,ScenarioCode:'CATA%20TOUL',ScenarioDisplayMode:display-standard,SearchGridFieldsShownOnResultsDTO:!(),SearchLabel:'',SearchTerms:'la%20bonne%20m%C3%A8re',SortField:!n,SortOrder:0,TemplateParams:(Scenario:'',Scope:TOULON,Size:!n,Source:'',Support:'',UseCompact:!f),UseSpellChecking:!n)))">La bonne mère</a>, Mathilda Di Matteo</p><img src="https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1747164570i/231494760.jpg" alt="mere" style="width:100px;"> <p> La bonne mère est l'histoire d'une mère et de sa fille que tout oppose. <br> Véro est une vraie "cagole" marseillaise. Elle aime le rose fushia, porter des vêtements moulants et sent bon (fort ?) le monoï. Elle n'a honte de rien. Les chapitres qui lui sont dédiés, vous pouvez être sûrs que vous les lirez avec l'accent de Marseille ! <br> <br> Clara, quant à elle, intello partie à Paris pour ses études, découvre un autre univers, bien plus policé et discret que tout ce qu’elle a connu jusque-là... <br> <br>L'histoire commence quand elle présente pour la première fois son petit ami à ses parents. Véro le trouve tout de suite bien trop bourgeois à son goût. On découvre alors qu’elles ne se comprennent absolument plus. Mais ont-elles un jour réellement fait partie du même monde ? Sauront-elles enfin se trouver ? <br>A la fois drôle et touchant, ce premier roman sent bon l’été et l’amour mère-fille. Il vient nous réchauffer en cette période hivernale et ça fait du bien ! <br> <br> LAURE Christelle</p> `,
];

const backgrounds = [
  'url("https://img.freepik.com/vecteurs-libre/modele-art-deco-premium-design-plat_23-2149150038.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://cdn.pixabay.com/photo/2023/01/23/13/37/flowers-7738726_640.jpg")',
  'url("https://cdn.pixabay.com/photo/2023/01/23/13/37/leaves-7738725_640.jpg")',
  'url("https://img.freepik.com/vecteurs-libre/illustration-motifs-aquarelle-tons-terre-doux_23-2151155711.jpg")',
  'url("https://img.freepik.com/free-vector/gradient-art-deco-pattern-design_23-2148981192.jpg?semt=ais_hybrid&w=740")',
  'url("https://img.freepik.com/photos-gratuite/conception-motifs-abstraits-sans-couture_23-2151179135.jpg")',
  'url("https://img.freepik.com/foto-gratis/diseno-patrones-costuras-abstractos_23-2151179214.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/photos-gratuite/conception-motifs-abstraits-sans-couture_23-2151179083.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/photos-gratuite/conception-abstraite-motifs-sans-couture_23-2151179066.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/conception-modele-mosaique-geometrique-plat_23-2149286388.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/photos-gratuite/modele-geometrique-sans-couture_23-2151021354.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-premium/motif-vectoriel-sans-couture-style-art-nouveau-papier-peint-design-vintage-decoratif-repetitif-floral_204216-1912.jpg")',
  'url("https://img.freepik.com/vecteurs-premium/natures-tapisserie-motifs-abstraits-tisses-terres-couleurs-motif-feuilles_334050-1582.jpg")',
  'url("https://img.freepik.com/vecteurs-premium/motifs-floraux-geometriques-modernes-du-milieu-du-siecle_1125044-70378.jpg")',
  'url("https://img.freepik.com/vecteurs-libre/motif-geometrique-groovy_23-2148888308.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/motif-geometrique-groovy_23-2148834199.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/vecteurs-libre/modele-sans-couture-groovy-circulaire-geometrique_23-2148825766.jpg")',
  'url("https://img.freepik.com/photos-premium/gros-plan-motif-feuilles-forme-eventail-fond-noir-ai-generative_955925-60248.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://img.freepik.com/photos-gratuite/conception-abstraite-motifs-sans-couture_23-2151179225.jpg?semt=ais_incoming&w=740&q=80")',
  'url("https://naldzgraphics.net/wp-content/uploads/2012/04/1-steampunk.jpg")',
  'url("https://img.freepik.com/psd-premium/modele-organique-art-nouveau-icone-organique-li-coulant-art-contour-abstrait-inspire-nature_1020495-548091.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/premium-vector/sepia-rose-gold-art-deco-pattern_23-2148664905.jpg")',
  'url("https://img.freepik.com/vecteurs-libre/motif-art-deco-degrade-elegant_23-2148965102.jpg?semt=ais_hybrid&w=740&q=80")',
  'url("https://img.freepik.com/photos-gratuite/conception-motifs-abstraits-sans-couture_23-2151179101.jpg?semt=ais_hybrid&w=740&q=80")'
];

const calendar = document.getElementById('calendar');

// 1. Créer un tableau [0, 1, 2, ..., 23] pour les indices
const indices = Array.from(Array(24).keys());

// 2. Mélanger les indices avec l'algorithme de Fisher-Yates
for (let i = indices.length - 1; i > 0; i--) {
  const j = Math.floor(Math.random() * (i + 1));
  [indices[i], indices[j]] = [indices[j], indices[i]];
}

// 3. Créer les cases dans l’ordre mélangé
indices.forEach(index => {
  const day = document.createElement('div');
  day.classList.add('day');

  const numberSpan = document.createElement('span');
  numberSpan.classList.add('day-number');
  numberSpan.textContent = index + 1;
  day.appendChild(numberSpan);

  day.setAttribute('data-message', messages[index]);

  // ✅ Appliquer le fond à motif ici
const bg = backgrounds[index % backgrounds.length];
  console.log(`Index: ${index}, Background: ${bg}`); // Ajout pour debug  
  day.style.backgroundImage = bg;
  day.style.backgroundSize = 'cover';
  day.style.backgroundPosition = 'center';
  day.style.backgroundRepeat = 'no-repeat';

 // Ajouter l'événement de clic avec contrôle sur la date
  day.addEventListener('click', function () {
    const now = new Date();
    const today = now.getDate();
    const currentMonth = now.getMonth() + 1; // mois de 1 à 12
    const dayNumber = parseInt(this.querySelector('.day-number').textContent);

    if (currentMonth === 12) {
      if (dayNumber <= today) {
        this.classList.add('opened');
        const modal = document.getElementById('modal');
        const modalMessage = document.getElementById('modal-message');
        modalMessage.innerHTML = this.getAttribute('data-message');
        modal.style.display = 'flex';
      } else {
        alert("Cette case ne peut pas encore être ouverte !");
      }
    } else {
      alert("Le calendrier est disponible uniquement en décembre !");
    }
  });

  calendar.appendChild(day);
});


// 4. Ajouter la case logo à la fin
const logoBox = document.createElement('div');
logoBox.classList.add('day', 'empty');

const logoImg = document.createElement('img');
logoImg.src = "logo.png";
logoImg.alt = "Logo";
logoImg.style.width = "100px";
logoImg.style.height = "auto";

logoBox.appendChild(logoImg);
calendar.appendChild(logoBox);

// Fermeture de la modale
const closeButton = document.querySelector('.close-button');
const modal = document.getElementById('modal');

closeButton.addEventListener('click', function () {
  modal.style.display = 'none';
});

// (optionnel) Fermer la modale en cliquant en dehors du contenu
window.addEventListener('click', function (event) {
  if (event.target === modal) {
    modal.style.display = 'none';
  }
});





